// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type Card struct {
	ID          string         `json:"id"`
	MatchID     string         `json:"match_id"`
	GameID      sql.NullString `json:"game_id"`
	TeamIndex   int64          `json:"team_index"`
	PlayerIndex int64          `json:"player_index"`
	CardType    string         `json:"card_type"`
	Reason      sql.NullString `json:"reason"`
	CreatedAt   sql.NullString `json:"created_at"`
}

type Game struct {
	ID         string         `json:"id"`
	MatchID    string         `json:"match_id"`
	GameNumber int64          `json:"game_number"`
	Team1Score int64          `json:"team1_score"`
	Team2Score int64          `json:"team2_score"`
	Status     string         `json:"status"`
	CreatedAt  sql.NullString `json:"created_at"`
	UpdatedAt  sql.NullString `json:"updated_at"`
}

type Match struct {
	ID             string         `json:"id"`
	Title          string         `json:"title"`
	ScheduledDate  string         `json:"scheduled_date"`
	Status         string         `json:"status"`
	CurrentGame    int64          `json:"current_game"`
	Team1P1Name    string         `json:"team1_p1_name"`
	Team1P2Name    sql.NullString `json:"team1_p2_name"`
	Team2P1Name    string         `json:"team2_p1_name"`
	Team2P2Name    sql.NullString `json:"team2_p2_name"`
	BestOf         int64          `json:"best_of"`
	Team1P1Country sql.NullString `json:"team1_p1_country"`
	Team1P2Country sql.NullString `json:"team1_p2_country"`
	Team2P1Country sql.NullString `json:"team2_p1_country"`
	Team2P2Country sql.NullString `json:"team2_p2_country"`
	Team1Timeout   bool           `json:"team1_timeout"`
	Team2Timeout   bool           `json:"team2_timeout"`
	CreatedAt      sql.NullString `json:"created_at"`
	UpdatedAt      sql.NullString `json:"updated_at"`
}
