// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
	"database/sql"
)

const createMatch = `-- name: CreateMatch :exec
INSERT INTO matches (
    id, title, scheduled_date, status, current_game,
    team1_p1_name, team1_p2_name, team2_p1_name, team2_p2_name
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateMatchParams struct {
	ID            string         `json:"id"`
	Title         string         `json:"title"`
	ScheduledDate string         `json:"scheduled_date"`
	Status        string         `json:"status"`
	CurrentGame   int64          `json:"current_game"`
	Team1P1Name   string         `json:"team1_p1_name"`
	Team1P2Name   sql.NullString `json:"team1_p2_name"`
	Team2P1Name   string         `json:"team2_p1_name"`
	Team2P2Name   sql.NullString `json:"team2_p2_name"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) error {
	_, err := q.db.ExecContext(ctx, createMatch,
		arg.ID,
		arg.Title,
		arg.ScheduledDate,
		arg.Status,
		arg.CurrentGame,
		arg.Team1P1Name,
		arg.Team1P2Name,
		arg.Team2P1Name,
		arg.Team2P2Name,
	)
	return err
}

const getUnstartedMatchesForPeriod = `-- name: GetUnstartedMatchesForPeriod :many
SELECT id, title, scheduled_date, status, current_game, team1_p1_name, team1_p2_name, team2_p1_name, team2_p2_name, created_at, updated_at FROM matches 
WHERE status = 'unstarted' 
  AND scheduled_date >= ? 
  AND scheduled_date <= ?
`

type GetUnstartedMatchesForPeriodParams struct {
	ScheduledDate   string `json:"scheduled_date"`
	ScheduledDate_2 string `json:"scheduled_date_2"`
}

func (q *Queries) GetUnstartedMatchesForPeriod(ctx context.Context, arg GetUnstartedMatchesForPeriodParams) ([]Match, error) {
	rows, err := q.db.QueryContext(ctx, getUnstartedMatchesForPeriod, arg.ScheduledDate, arg.ScheduledDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ScheduledDate,
			&i.Status,
			&i.CurrentGame,
			&i.Team1P1Name,
			&i.Team1P2Name,
			&i.Team2P1Name,
			&i.Team2P2Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
