// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	// LockExpiry = 600s (see service.LockExpiry constant)
	AcquireMatchLock(ctx context.Context, arg AcquireMatchLockParams) (sql.Result, error)
	AdminUpdateMatch(ctx context.Context, arg AdminUpdateMatchParams) error
	ClearCardsForMatch(ctx context.Context, matchID string) error
	CreateCard(ctx context.Context, arg CreateCardParams) error
	CreateMatch(ctx context.Context, arg CreateMatchParams) error
	DeleteGamesForMatch(ctx context.Context, matchID string) error
	DeleteMatch(ctx context.Context, id string) error
	DeleteMatches(ctx context.Context, ids []string) error
	GetAllMatches(ctx context.Context) ([]GetAllMatchesRow, error)
	GetAllMatchesWithGames(ctx context.Context) ([]GetAllMatchesWithGamesRow, error)
	GetCardsForMatch(ctx context.Context, matchID string) ([]Card, error)
	GetGameIDByNumber(ctx context.Context, arg GetGameIDByNumberParams) (string, error)
	GetGamesForMatch(ctx context.Context, matchID string) ([]Game, error)
	GetIncompleteMatchesForPeriod(ctx context.Context, arg GetIncompleteMatchesForPeriodParams) ([]GetIncompleteMatchesForPeriodRow, error)
	GetMatch(ctx context.Context, id string) (GetMatchRow, error)
	GetMatchLock(ctx context.Context, matchID string) (MatchLock, error)
	// LockExpiry = 600s (see service.LockExpiry constant)
	PruneExpiredLocks(ctx context.Context) error
	ReleaseMatchLock(ctx context.Context, matchID string) error
	TouchMatchLock(ctx context.Context, arg TouchMatchLockParams) (sql.Result, error)
	UpdateMatchState(ctx context.Context, arg UpdateMatchStateParams) error
	UpdateMatchStatus(ctx context.Context, arg UpdateMatchStatusParams) error
	UpsertGame(ctx context.Context, arg UpsertGameParams) (string, error)
}

var _ Querier = (*Queries)(nil)
