// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	CreateMatch(ctx context.Context, arg CreateMatchParams) error
	GetUnstartedMatchesForPeriod(ctx context.Context, arg GetUnstartedMatchesForPeriodParams) ([]Match, error)
}

var _ Querier = (*Queries)(nil)
