// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
	"database/sql"
)

const clearCardsForMatch = `-- name: ClearCardsForMatch :exec
DELETE FROM cards WHERE match_id = ?
`

func (q *Queries) ClearCardsForMatch(ctx context.Context, matchID string) error {
	_, err := q.db.ExecContext(ctx, clearCardsForMatch, matchID)
	return err
}

const createCard = `-- name: CreateCard :exec
INSERT INTO cards (id, match_id, game_id, team_index, player_index, card_type, reason)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateCardParams struct {
	ID          string         `json:"id"`
	MatchID     string         `json:"match_id"`
	GameID      sql.NullString `json:"game_id"`
	TeamIndex   int64          `json:"team_index"`
	PlayerIndex int64          `json:"player_index"`
	CardType    string         `json:"card_type"`
	Reason      sql.NullString `json:"reason"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) error {
	_, err := q.db.ExecContext(ctx, createCard,
		arg.ID,
		arg.MatchID,
		arg.GameID,
		arg.TeamIndex,
		arg.PlayerIndex,
		arg.CardType,
		arg.Reason,
	)
	return err
}

const createMatch = `-- name: CreateMatch :exec
INSERT INTO matches (
    id, title, scheduled_date, status, current_game,
    team1_p1_name, team1_p2_name, team2_p1_name, team2_p2_name,
    best_of, team1_p1_country, team1_p2_country, team2_p1_country, team2_p2_country
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateMatchParams struct {
	ID             string         `json:"id"`
	Title          string         `json:"title"`
	ScheduledDate  string         `json:"scheduled_date"`
	Status         string         `json:"status"`
	CurrentGame    int64          `json:"current_game"`
	Team1P1Name    string         `json:"team1_p1_name"`
	Team1P2Name    sql.NullString `json:"team1_p2_name"`
	Team2P1Name    string         `json:"team2_p1_name"`
	Team2P2Name    sql.NullString `json:"team2_p2_name"`
	BestOf         int64          `json:"best_of"`
	Team1P1Country sql.NullString `json:"team1_p1_country"`
	Team1P2Country sql.NullString `json:"team1_p2_country"`
	Team2P1Country sql.NullString `json:"team2_p1_country"`
	Team2P2Country sql.NullString `json:"team2_p2_country"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) error {
	_, err := q.db.ExecContext(ctx, createMatch,
		arg.ID,
		arg.Title,
		arg.ScheduledDate,
		arg.Status,
		arg.CurrentGame,
		arg.Team1P1Name,
		arg.Team1P2Name,
		arg.Team2P1Name,
		arg.Team2P2Name,
		arg.BestOf,
		arg.Team1P1Country,
		arg.Team1P2Country,
		arg.Team2P1Country,
		arg.Team2P2Country,
	)
	return err
}

const getUnstartedMatchesForPeriod = `-- name: GetUnstartedMatchesForPeriod :many
SELECT id, title, scheduled_date, status, current_game, team1_p1_name, team1_p2_name, team2_p1_name, team2_p2_name, best_of, team1_p1_country, team1_p2_country, team2_p1_country, team2_p2_country, created_at, updated_at FROM matches 
WHERE status = 'unstarted' 
  AND scheduled_date >= ? 
  AND scheduled_date <= ?
`

type GetUnstartedMatchesForPeriodParams struct {
	ScheduledDate   string `json:"scheduled_date"`
	ScheduledDate_2 string `json:"scheduled_date_2"`
}

func (q *Queries) GetUnstartedMatchesForPeriod(ctx context.Context, arg GetUnstartedMatchesForPeriodParams) ([]Match, error) {
	rows, err := q.db.QueryContext(ctx, getUnstartedMatchesForPeriod, arg.ScheduledDate, arg.ScheduledDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ScheduledDate,
			&i.Status,
			&i.CurrentGame,
			&i.Team1P1Name,
			&i.Team1P2Name,
			&i.Team2P1Name,
			&i.Team2P2Name,
			&i.BestOf,
			&i.Team1P1Country,
			&i.Team1P2Country,
			&i.Team2P1Country,
			&i.Team2P2Country,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMatchStatus = `-- name: UpdateMatchStatus :exec
UPDATE matches 
SET status = ?, current_game = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateMatchStatusParams struct {
	Status      string `json:"status"`
	CurrentGame int64  `json:"current_game"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateMatchStatus(ctx context.Context, arg UpdateMatchStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMatchStatus, arg.Status, arg.CurrentGame, arg.ID)
	return err
}

const upsertGame = `-- name: UpsertGame :exec
INSERT INTO games (id, match_id, game_number, team1_score, team2_score, status)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(match_id, game_number) DO UPDATE SET
    team1_score = excluded.team1_score,
    team2_score = excluded.team2_score,
    status = excluded.status,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertGameParams struct {
	ID         string `json:"id"`
	MatchID    string `json:"match_id"`
	GameNumber int64  `json:"game_number"`
	Team1Score int64  `json:"team1_score"`
	Team2Score int64  `json:"team2_score"`
	Status     string `json:"status"`
}

func (q *Queries) UpsertGame(ctx context.Context, arg UpsertGameParams) error {
	_, err := q.db.ExecContext(ctx, upsertGame,
		arg.ID,
		arg.MatchID,
		arg.GameNumber,
		arg.Team1Score,
		arg.Team2Score,
		arg.Status,
	)
	return err
}
