// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
	"database/sql"
	"strings"
)

const acquireMatchLock = `-- name: AcquireMatchLock :execresult
INSERT INTO match_locks (match_id, session_id, last_sync)
VALUES (?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(match_id) DO UPDATE SET
    session_id = excluded.session_id,
    last_sync = excluded.last_sync
WHERE match_locks.last_sync < datetime('now', '-30 seconds')
`

type AcquireMatchLockParams struct {
	MatchID   string `json:"match_id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) AcquireMatchLock(ctx context.Context, arg AcquireMatchLockParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, acquireMatchLock, arg.MatchID, arg.SessionID)
}

const adminUpdateMatch = `-- name: AdminUpdateMatch :exec
UPDATE matches SET status = ?, remarks = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type AdminUpdateMatchParams struct {
	Status  string         `json:"status"`
	Remarks sql.NullString `json:"remarks"`
	ID      string         `json:"id"`
}

func (q *Queries) AdminUpdateMatch(ctx context.Context, arg AdminUpdateMatchParams) error {
	_, err := q.db.ExecContext(ctx, adminUpdateMatch, arg.Status, arg.Remarks, arg.ID)
	return err
}

const clearCardsForMatch = `-- name: ClearCardsForMatch :exec
DELETE FROM cards WHERE match_id = ?
`

func (q *Queries) ClearCardsForMatch(ctx context.Context, matchID string) error {
	_, err := q.db.ExecContext(ctx, clearCardsForMatch, matchID)
	return err
}

const createCard = `-- name: CreateCard :exec
INSERT INTO cards (id, match_id, game_id, team_index, player_index, card_type, reason)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateCardParams struct {
	ID          string         `json:"id"`
	MatchID     string         `json:"match_id"`
	GameID      sql.NullString `json:"game_id"`
	TeamIndex   int64          `json:"team_index"`
	PlayerIndex int64          `json:"player_index"`
	CardType    string         `json:"card_type"`
	Reason      sql.NullString `json:"reason"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) error {
	_, err := q.db.ExecContext(ctx, createCard,
		arg.ID,
		arg.MatchID,
		arg.GameID,
		arg.TeamIndex,
		arg.PlayerIndex,
		arg.CardType,
		arg.Reason,
	)
	return err
}

const createMatch = `-- name: CreateMatch :exec
INSERT INTO matches (
    id, title, scheduled_date, status, current_game,
    team1_p1_name, team1_p2_name, team2_p1_name, team2_p2_name,
    best_of, team1_p1_country, team1_p2_country, team2_p1_country, team2_p2_country,
    table_number
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateMatchParams struct {
	ID             string         `json:"id"`
	Title          string         `json:"title"`
	ScheduledDate  string         `json:"scheduled_date"`
	Status         string         `json:"status"`
	CurrentGame    int64          `json:"current_game"`
	Team1P1Name    string         `json:"team1_p1_name"`
	Team1P2Name    sql.NullString `json:"team1_p2_name"`
	Team2P1Name    string         `json:"team2_p1_name"`
	Team2P2Name    sql.NullString `json:"team2_p2_name"`
	BestOf         int64          `json:"best_of"`
	Team1P1Country sql.NullString `json:"team1_p1_country"`
	Team1P2Country sql.NullString `json:"team1_p2_country"`
	Team2P1Country sql.NullString `json:"team2_p1_country"`
	Team2P2Country sql.NullString `json:"team2_p2_country"`
	TableNumber    sql.NullInt64  `json:"table_number"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) error {
	_, err := q.db.ExecContext(ctx, createMatch,
		arg.ID,
		arg.Title,
		arg.ScheduledDate,
		arg.Status,
		arg.CurrentGame,
		arg.Team1P1Name,
		arg.Team1P2Name,
		arg.Team2P1Name,
		arg.Team2P2Name,
		arg.BestOf,
		arg.Team1P1Country,
		arg.Team1P2Country,
		arg.Team2P1Country,
		arg.Team2P2Country,
		arg.TableNumber,
	)
	return err
}

const deleteGamesForMatch = `-- name: DeleteGamesForMatch :exec
DELETE FROM games WHERE match_id = ?
`

func (q *Queries) DeleteGamesForMatch(ctx context.Context, matchID string) error {
	_, err := q.db.ExecContext(ctx, deleteGamesForMatch, matchID)
	return err
}

const deleteMatch = `-- name: DeleteMatch :exec
DELETE FROM matches WHERE id = ?
`

func (q *Queries) DeleteMatch(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMatch, id)
	return err
}

const deleteMatches = `-- name: DeleteMatches :exec
DELETE FROM matches WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) DeleteMatches(ctx context.Context, ids []string) error {
	query := deleteMatches
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const getAllMatches = `-- name: GetAllMatches :many
SELECT id, title, scheduled_date, status, current_game, team1_p1_name, team1_p2_name, team2_p1_name, team2_p2_name, best_of, team1_p1_country, team1_p2_country, team2_p1_country, team2_p2_country, created_at, updated_at, state_json, table_number, remarks FROM matches 
ORDER BY scheduled_date DESC
`

type GetAllMatchesRow struct {
	ID             string         `json:"id"`
	Title          string         `json:"title"`
	ScheduledDate  string         `json:"scheduled_date"`
	Status         string         `json:"status"`
	CurrentGame    int64          `json:"current_game"`
	Team1P1Name    string         `json:"team1_p1_name"`
	Team1P2Name    sql.NullString `json:"team1_p2_name"`
	Team2P1Name    string         `json:"team2_p1_name"`
	Team2P2Name    sql.NullString `json:"team2_p2_name"`
	BestOf         int64          `json:"best_of"`
	Team1P1Country sql.NullString `json:"team1_p1_country"`
	Team1P2Country sql.NullString `json:"team1_p2_country"`
	Team2P1Country sql.NullString `json:"team2_p1_country"`
	Team2P2Country sql.NullString `json:"team2_p2_country"`
	CreatedAt      sql.NullString `json:"created_at"`
	UpdatedAt      sql.NullString `json:"updated_at"`
	StateJson      sql.NullString `json:"state_json"`
	TableNumber    sql.NullInt64  `json:"table_number"`
	Remarks        sql.NullString `json:"remarks"`
}

func (q *Queries) GetAllMatches(ctx context.Context) ([]GetAllMatchesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllMatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllMatchesRow
	for rows.Next() {
		var i GetAllMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ScheduledDate,
			&i.Status,
			&i.CurrentGame,
			&i.Team1P1Name,
			&i.Team1P2Name,
			&i.Team2P1Name,
			&i.Team2P2Name,
			&i.BestOf,
			&i.Team1P1Country,
			&i.Team1P2Country,
			&i.Team2P1Country,
			&i.Team2P2Country,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StateJson,
			&i.TableNumber,
			&i.Remarks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMatchesWithGames = `-- name: GetAllMatchesWithGames :many
SELECT
    m.id, m.title, m.scheduled_date, m.status, m.table_number,
    m.team1_p1_name, m.team1_p2_name, m.team2_p1_name, m.team2_p2_name,
    m.team1_p1_country, m.team1_p2_country, m.team2_p1_country, m.team2_p2_country,
    m.best_of,
    g.id AS game_id, g.game_number, g.team1_score, g.team2_score, g.status AS game_status
FROM matches m
LEFT JOIN games g ON m.id = g.match_id
ORDER BY m.scheduled_date ASC, g.game_number ASC
`

type GetAllMatchesWithGamesRow struct {
	ID             string         `json:"id"`
	Title          string         `json:"title"`
	ScheduledDate  string         `json:"scheduled_date"`
	Status         string         `json:"status"`
	TableNumber    sql.NullInt64  `json:"table_number"`
	Team1P1Name    string         `json:"team1_p1_name"`
	Team1P2Name    sql.NullString `json:"team1_p2_name"`
	Team2P1Name    string         `json:"team2_p1_name"`
	Team2P2Name    sql.NullString `json:"team2_p2_name"`
	Team1P1Country sql.NullString `json:"team1_p1_country"`
	Team1P2Country sql.NullString `json:"team1_p2_country"`
	Team2P1Country sql.NullString `json:"team2_p1_country"`
	Team2P2Country sql.NullString `json:"team2_p2_country"`
	BestOf         int64          `json:"best_of"`
	GameID         sql.NullString `json:"game_id"`
	GameNumber     sql.NullInt64  `json:"game_number"`
	Team1Score     sql.NullInt64  `json:"team1_score"`
	Team2Score     sql.NullInt64  `json:"team2_score"`
	GameStatus     sql.NullString `json:"game_status"`
}

func (q *Queries) GetAllMatchesWithGames(ctx context.Context) ([]GetAllMatchesWithGamesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllMatchesWithGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllMatchesWithGamesRow
	for rows.Next() {
		var i GetAllMatchesWithGamesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ScheduledDate,
			&i.Status,
			&i.TableNumber,
			&i.Team1P1Name,
			&i.Team1P2Name,
			&i.Team2P1Name,
			&i.Team2P2Name,
			&i.Team1P1Country,
			&i.Team1P2Country,
			&i.Team2P1Country,
			&i.Team2P2Country,
			&i.BestOf,
			&i.GameID,
			&i.GameNumber,
			&i.Team1Score,
			&i.Team2Score,
			&i.GameStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardsForMatch = `-- name: GetCardsForMatch :many
SELECT id, match_id, game_id, team_index, player_index, card_type, reason, created_at FROM cards 
WHERE match_id = ?
`

func (q *Queries) GetCardsForMatch(ctx context.Context, matchID string) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getCardsForMatch, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.GameID,
			&i.TeamIndex,
			&i.PlayerIndex,
			&i.CardType,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameIDByNumber = `-- name: GetGameIDByNumber :one
SELECT id FROM games WHERE match_id = ? AND game_number = ?
`

type GetGameIDByNumberParams struct {
	MatchID    string `json:"match_id"`
	GameNumber int64  `json:"game_number"`
}

func (q *Queries) GetGameIDByNumber(ctx context.Context, arg GetGameIDByNumberParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getGameIDByNumber, arg.MatchID, arg.GameNumber)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getGamesForMatch = `-- name: GetGamesForMatch :many
SELECT id, match_id, game_number, team1_score, team2_score, status, created_at, updated_at FROM games 
WHERE match_id = ? 
ORDER BY game_number
`

func (q *Queries) GetGamesForMatch(ctx context.Context, matchID string) ([]Game, error) {
	rows, err := q.db.QueryContext(ctx, getGamesForMatch, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.GameNumber,
			&i.Team1Score,
			&i.Team2Score,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIncompleteMatchesForPeriod = `-- name: GetIncompleteMatchesForPeriod :many
SELECT id, title, scheduled_date, status, current_game, team1_p1_name, team1_p2_name, team2_p1_name, team2_p2_name, best_of, team1_p1_country, team1_p2_country, team2_p1_country, team2_p2_country, created_at, updated_at, state_json, table_number, remarks FROM matches 
WHERE status != 'completed' 
  AND scheduled_date >= ? 
  AND scheduled_date <= ?
`

type GetIncompleteMatchesForPeriodParams struct {
	ScheduledDate   string `json:"scheduled_date"`
	ScheduledDate_2 string `json:"scheduled_date_2"`
}

type GetIncompleteMatchesForPeriodRow struct {
	ID             string         `json:"id"`
	Title          string         `json:"title"`
	ScheduledDate  string         `json:"scheduled_date"`
	Status         string         `json:"status"`
	CurrentGame    int64          `json:"current_game"`
	Team1P1Name    string         `json:"team1_p1_name"`
	Team1P2Name    sql.NullString `json:"team1_p2_name"`
	Team2P1Name    string         `json:"team2_p1_name"`
	Team2P2Name    sql.NullString `json:"team2_p2_name"`
	BestOf         int64          `json:"best_of"`
	Team1P1Country sql.NullString `json:"team1_p1_country"`
	Team1P2Country sql.NullString `json:"team1_p2_country"`
	Team2P1Country sql.NullString `json:"team2_p1_country"`
	Team2P2Country sql.NullString `json:"team2_p2_country"`
	CreatedAt      sql.NullString `json:"created_at"`
	UpdatedAt      sql.NullString `json:"updated_at"`
	StateJson      sql.NullString `json:"state_json"`
	TableNumber    sql.NullInt64  `json:"table_number"`
	Remarks        sql.NullString `json:"remarks"`
}

func (q *Queries) GetIncompleteMatchesForPeriod(ctx context.Context, arg GetIncompleteMatchesForPeriodParams) ([]GetIncompleteMatchesForPeriodRow, error) {
	rows, err := q.db.QueryContext(ctx, getIncompleteMatchesForPeriod, arg.ScheduledDate, arg.ScheduledDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIncompleteMatchesForPeriodRow
	for rows.Next() {
		var i GetIncompleteMatchesForPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ScheduledDate,
			&i.Status,
			&i.CurrentGame,
			&i.Team1P1Name,
			&i.Team1P2Name,
			&i.Team2P1Name,
			&i.Team2P2Name,
			&i.BestOf,
			&i.Team1P1Country,
			&i.Team1P2Country,
			&i.Team2P1Country,
			&i.Team2P2Country,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StateJson,
			&i.TableNumber,
			&i.Remarks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatch = `-- name: GetMatch :one
SELECT id, title, scheduled_date, status, current_game, team1_p1_name, team1_p2_name, team2_p1_name, team2_p2_name, best_of, team1_p1_country, team1_p2_country, team2_p1_country, team2_p2_country, created_at, updated_at, state_json, table_number, remarks FROM matches WHERE id = ?
`

type GetMatchRow struct {
	ID             string         `json:"id"`
	Title          string         `json:"title"`
	ScheduledDate  string         `json:"scheduled_date"`
	Status         string         `json:"status"`
	CurrentGame    int64          `json:"current_game"`
	Team1P1Name    string         `json:"team1_p1_name"`
	Team1P2Name    sql.NullString `json:"team1_p2_name"`
	Team2P1Name    string         `json:"team2_p1_name"`
	Team2P2Name    sql.NullString `json:"team2_p2_name"`
	BestOf         int64          `json:"best_of"`
	Team1P1Country sql.NullString `json:"team1_p1_country"`
	Team1P2Country sql.NullString `json:"team1_p2_country"`
	Team2P1Country sql.NullString `json:"team2_p1_country"`
	Team2P2Country sql.NullString `json:"team2_p2_country"`
	CreatedAt      sql.NullString `json:"created_at"`
	UpdatedAt      sql.NullString `json:"updated_at"`
	StateJson      sql.NullString `json:"state_json"`
	TableNumber    sql.NullInt64  `json:"table_number"`
	Remarks        sql.NullString `json:"remarks"`
}

func (q *Queries) GetMatch(ctx context.Context, id string) (GetMatchRow, error) {
	row := q.db.QueryRowContext(ctx, getMatch, id)
	var i GetMatchRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ScheduledDate,
		&i.Status,
		&i.CurrentGame,
		&i.Team1P1Name,
		&i.Team1P2Name,
		&i.Team2P1Name,
		&i.Team2P2Name,
		&i.BestOf,
		&i.Team1P1Country,
		&i.Team1P2Country,
		&i.Team2P1Country,
		&i.Team2P2Country,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StateJson,
		&i.TableNumber,
		&i.Remarks,
	)
	return i, err
}

const getMatchLock = `-- name: GetMatchLock :one
SELECT match_id, session_id, last_sync FROM match_locks WHERE match_id = ?
`

func (q *Queries) GetMatchLock(ctx context.Context, matchID string) (MatchLock, error) {
	row := q.db.QueryRowContext(ctx, getMatchLock, matchID)
	var i MatchLock
	err := row.Scan(&i.MatchID, &i.SessionID, &i.LastSync)
	return i, err
}

const pruneExpiredLocks = `-- name: PruneExpiredLocks :exec
DELETE FROM match_locks WHERE last_sync < datetime('now', '-30 seconds')
`

func (q *Queries) PruneExpiredLocks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, pruneExpiredLocks)
	return err
}

const releaseMatchLock = `-- name: ReleaseMatchLock :exec
DELETE FROM match_locks WHERE match_id = ?
`

func (q *Queries) ReleaseMatchLock(ctx context.Context, matchID string) error {
	_, err := q.db.ExecContext(ctx, releaseMatchLock, matchID)
	return err
}

const touchMatchLock = `-- name: TouchMatchLock :execresult
UPDATE match_locks SET last_sync = CURRENT_TIMESTAMP
WHERE match_id = ? AND session_id = ?
`

type TouchMatchLockParams struct {
	MatchID   string `json:"match_id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) TouchMatchLock(ctx context.Context, arg TouchMatchLockParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, touchMatchLock, arg.MatchID, arg.SessionID)
}

const updateMatchState = `-- name: UpdateMatchState :exec
UPDATE matches 
SET status = ?, 
    current_game = ?, 
    state_json = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateMatchStateParams struct {
	Status      string         `json:"status"`
	CurrentGame int64          `json:"current_game"`
	StateJson   sql.NullString `json:"state_json"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateMatchState(ctx context.Context, arg UpdateMatchStateParams) error {
	_, err := q.db.ExecContext(ctx, updateMatchState,
		arg.Status,
		arg.CurrentGame,
		arg.StateJson,
		arg.ID,
	)
	return err
}

const updateMatchStatus = `-- name: UpdateMatchStatus :exec
UPDATE matches 
SET status = ?, 
    current_game = ?, 
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateMatchStatusParams struct {
	Status      string `json:"status"`
	CurrentGame int64  `json:"current_game"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateMatchStatus(ctx context.Context, arg UpdateMatchStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMatchStatus, arg.Status, arg.CurrentGame, arg.ID)
	return err
}

const upsertGame = `-- name: UpsertGame :one
INSERT INTO games (id, match_id, game_number, team1_score, team2_score, status)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(match_id, game_number) DO UPDATE SET
    team1_score = excluded.team1_score,
    team2_score = excluded.team2_score,
    status = excluded.status,
    updated_at = CURRENT_TIMESTAMP
RETURNING id
`

type UpsertGameParams struct {
	ID         string `json:"id"`
	MatchID    string `json:"match_id"`
	GameNumber int64  `json:"game_number"`
	Team1Score int64  `json:"team1_score"`
	Team2Score int64  `json:"team2_score"`
	Status     string `json:"status"`
}

func (q *Queries) UpsertGame(ctx context.Context, arg UpsertGameParams) (string, error) {
	row := q.db.QueryRowContext(ctx, upsertGame,
		arg.ID,
		arg.MatchID,
		arg.GameNumber,
		arg.Team1Score,
		arg.Team2Score,
		arg.Status,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
