// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	ClearCardsForMatch(ctx context.Context, matchID string) error
	CreateCard(ctx context.Context, arg CreateCardParams) error
	CreateMatch(ctx context.Context, arg CreateMatchParams) error
	GetUnstartedMatchesForPeriod(ctx context.Context, arg GetUnstartedMatchesForPeriodParams) ([]Match, error)
	UpdateMatchStatus(ctx context.Context, arg UpdateMatchStatusParams) error
	UpsertGame(ctx context.Context, arg UpsertGameParams) error
}

var _ Querier = (*Queries)(nil)
